[package]
name = "divvun-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
box-format = { version = "0.3.2", default-features = false, features = ["reader"] }
# pyo3 = { version = "0.20.0", features = ["abi3-py311"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_path_to_error = "0.1.14"
tempfile = "3.8.1"
tokio = { version = "1.29.1", features = ["full"] }
