[package]
name = "divvun-runtime"
version = "0.1.0"
edition = "2021"

[lib]
name = "divvun_runtime"
crate-type = ["cdylib", "staticlib", "lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.77"
box-format = { git = "https://github.com/bbqsrc/box", default-features = false, features = ["reader"] }
cg3 = { version = "0.1.0", git = "ssh://git@github.com/necessary-nu/cg3-rs" }
divvunspell = { git = "https://github.com/divvun/divvunspell", version = "1.0.0-beta.3" }
hfst = { version = "0.1.0", git = "ssh://git@github.com/necessary-nu/hfst-rs" }
inventory = "0.3.15"
log = "0.4.20"
once_cell = "1.19.0"
oslog = "0.2.0"
pyo3 = { version = "0.20.0", features = ["abi3-py311", "auto-initialize"] }
regex = "1.10.3"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_path_to_error = "0.1.14"
tempfile = "3.8.1"
thiserror = "1.0.56"
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
wav_io = "0.1.12"

[profile.dev]
incremental = false

[profile.dev.package."*"]
opt-level = 3