[package]
name = "divvun-runtime-macros"
version = "0.2.4"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
unsynn = "0.1.1"
